[versions]
# The latest versions are available at https://lambdaurora.dev/tools/import_quilt.html
minecraft = "1.19.3"
quilt_mappings = "1.19.3+build.28"
quilt_loader = "0.19.0"

switchy = "2.1.7+1.19"

quilted_fabric_api = "5.0.0-beta.9+0.76.0-1.19.3"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
quilt_mappings = { module = "org.quiltmc:quilt-mappings", version.ref = "quilt_mappings" }
quilt_loader = { module = "org.quiltmc:quilt-loader", version.ref = "quilt_loader" }

switchy = { module = "folk.sisby:switchy-core", version.ref = "switchy" }
switchy_client = { module = "folk.sisby:switchy-client", version.ref = "switchy" }
switchy_ui = { module = "folk.sisby:switchy-ui", version.ref = "switchy" }

quilted_fabric_api = { module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api", version.ref = "quilted_fabric_api" }
quilted_fabric_api_deprecated = { module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api-deprecated", version.ref = "quilted_fabric_api" }

# If you have multiple similar dependencies, you can declare a dependency bundle and reference it on the build script with "libs.bundles.example".
[bundles]
quilted_fabric_api = ["quilted_fabric_api", "quilted_fabric_api_deprecated"]

[plugins]
quilt_loom = { id = "org.quiltmc.loom", version = "1.2.+" }
